version: '3.8'
services:
  web:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: chatgpt_app
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../..:/app:ro
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable-alpine
    container_name: chatgpt_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/chatgpt.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../static:/app/static:ro
    depends_on:
      - web
